### ISSUE TITLE
[BUG] Import logic broken when event goes between two months

### ISSUE THREAD

**Issue by adriancast** [adriancast/kronobot#33]
Current logic to sync data is:
```
today = datetime.now()
events_to_sync = EventModel.objects.filter(
    start_date__year=today.year, start_date__month=today.month, provider_name=EventProvider.KRONOLIVE
).order_by("start_date")
```

For this reasson, if a event occurs between two months the data import will not work properly.
Data to sync should be from 30 days before the execution time to 30 days after the execution time

I think this should be fixed adding some logic like:
```
min_start_date_filter = datetime.now() - timedelta(days=30)
max_start_date_filter = datetime.now() + timedelta(days=30)
EventModel.objects.filter(
    start_date__gte=min_start_date_filter, start_date__lte=max_start_date_filter, provider_name=EventProvider.KRONOLIVE
)
```

This should be fixed in the files:
- app/kronolive/management/commands/import_kronolive_inscriptions.py
- app/kronolive/management/commands/import_kronolive_section_times.py

**Comment by antoniahp** [comment]
from django.db.models import Q

min_start_date_filter = datetime.now() - timedelta(days=30)
max_start_date_filter = datetime.now() + timedelta(days=30)

events_to_sync = EventModel.objects.filter(
    Q(start_date__gte=min_start_date_filter, end_date__lte=max_start_date_filter) |
    Q(start_date__lte=max_start_date_filter, end_date__gte=min_start_date_filter),
    provider_name=EventProvider.KRONOLIVE
).order_by("start_date")

**Comment by VidyaYadavv1519** [comment]
from datetime import datetime, timedelta
from your_app.models import EventModel, EventProvider

min_start_date_filter = datetime.now() - timedelta(days=30)
max_start_date_filter = datetime.now() + timedelta(days=30)

events_to_sync = EventModel.objects.filter(
    start_date__gte=min_start_date_filter,
    start_date__lte=max_start_date_filter,
    provider_name=EventProvider.KRONOLIVE
).order_by("start_date")                                                                                                                                                                                       This code will fetch events that occurred within the specified 60-day window, and the result will be ordered by the start_date. Make sure to replace "your_app" with the actual name of your Django app where the EventModel and EventProvider are defined.
